baseURL = "https://www.raffaelespataro.it/"

languageCode = 'en-us'

title = 'Raffaele Spataro'

theme = "m10c"

author = "Raffaeele Spataro"

description = "Welcome to my blog! I share insights on coding, my projects, and occasional snippets of my life. Enjoy exploring!"

publishDir = "docs"

contentDir = "content"

defaultContentLanguage = "en"

enableEmoji = "true"

enableGitInfo = "true"

disqusShortname = "https-www-raffaelespataro-it"


[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 2
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 3

[params]
    author = "Raffaele Spataro"
    description = "Welcome to my blog! I share insights on coding, my projects, and occasional snippets of my life. Enjoy exploring!"
    menu_item_separator = " - "
    avatar = "avataaars.png"

    [[params.social]]
        icon = "linkedin"
        name = "linkedin"
        url = "https://www.linkedin.com/in/raffaele-spataro-44194b57/"
    [[params.social]]
        icon = "github"
        name = "github"
        url = "https://github.com/raphael2692"

[params.style]
    primaryColor = "#0e76a8"